# # Running Semantic Functions Inline

import semantic_kernel as sk
from semantic_kernel.connectors.ai.open_ai import AzureChatCompletion

kernel = sk.Kernel()

deployment, api_key, endpoint = sk.azure_openai_settings_from_dot_env()

kernel.add_chat_service(
        "chat_completion",
        AzureChatCompletion(deployment_name=deployment, endpoint=endpoint, api_key=api_key),
)

# First Example----------------------------------------------------------

prompt = """{{$input}}
Summarize the content above.
"""

summarize = kernel.create_semantic_function(prompt_template=prompt, max_tokens=2000, temperature=0.2, top_p=0.5)

input_text = """
In accounting, revenue is the total amount of income generated by the sale of goods and services related to the primary operations of the business.[1] Commercial revenue may also be referred to as sales or as turnover. Some companies receive revenue from interest, royalties, or other fees.[2] "Revenue" may refer to income in general, or it may refer to the amount, in a monetary unit, earned during a period of time, as in "Last year, Company X had revenue of $42 million". Profits or net income generally imply total revenue minus total expenses in a given period. In accounting, revenue is a subsection of the Equity section of the balance statement, since it increases equity. It is often referred to as the "top line" due to its position at the very top of the income statement. This is to be contrasted with the "bottom line" which denotes net income (gross revenues minus total expenses).[3]
In general usage, revenue is the total amount of income by the sale of goods or services related to the company's operations. Sales revenue is income received from selling goods or services over a period of time. Tax revenue is income that a government receives from taxpayers. Fundraising revenue is income received by a charity from donors etc. to further its social purposes.
"""
summary = summarize(input_text)
print(summary)

# Second example-----------------------------------------------------------
sk_prompt = """
{{$input}}

Give me the TLDR in 5 words or less.
"""

text = """
    1) A robot may not injure a human being or, through inaction,
    allow a human being to come to harm.

    2) A robot must obey orders given it by human beings except where
    such orders would conflict with the First Law.

    3) A robot must protect its own existence as long as such protection
    does not conflict with the First or Second Law.
"""

tldr_function = kernel.create_semantic_function(prompt_template=sk_prompt, max_tokens=200, temperature=0, top_p=0.5)

summary = tldr_function(text)

print(f"Output: {summary}")  # Output: Robots must not harm humans.


